#!/usr/bin/env python3
"""Plot data generated by scripts/run_experiments.py or scripts/train.py."""
import argparse
import csv
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

def read_csv(filename):
    with open(filename,newline='') as f: return list(csv.DictReader(f))

def plot_throughput(rows,out):
    experiments = [('bandwidth_mhz','Bandwidth (MHz)','fig3_bandwidth'),
                   ('power_w','Transmission power (W)','fig3_power'),
                   ('num_edges','Number of subchannels','fig4_edge_count'),
                   ('ues_per_edge','UEs per subchannel','fig4_users'),
                   ('power_allocation','Transmission power (W)','fig5_power_allocation')]
    for kind,label,filename in experiments:
        filtered=[r for r in rows if r['experiment']==kind]
        if not filtered:continue
        fig,ax=plt.subplots(figsize=(6,4))
        for scheme in dict.fromkeys(r['access'] for r in filtered):
            group=sorted([r for r in filtered if r['access']==scheme],key=lambda x:float(x['x']))
            ax.plot([float(r['x']) for r in group],
                    [float(r['throughput_mbps']) for r in group],'-o',label=scheme.upper())
        ax.set(xlabel=label,ylabel='Total throughput (Mbps)')
        ax.legend();ax.grid(True,alpha=0.25)
        fig.tight_layout();fig.savefig(out/f'{filename}.png',dpi=180)
        plt.close(fig)

def plot_training(rows,out):
    fig,ax=plt.subplots(figsize=(6,4))
    rows=sorted(rows,key=lambda x:int(x['episode']))
    ax.plot([int(r['episode']) for r in rows],[float(r['reward']) for r in rows])
    ax.set(xlabel='Episode',ylabel='Mean training reward')
    ax.grid(True,alpha=0.25);fig.tight_layout()
    fig.savefig(out/'reward_convergence.png',dpi=180);plt.close(fig)

def plot_policy_sweep(rows,out):
    if 'algorithm' not in rows[0]:return
    if 'task_size_mb' in rows[0] and len({float(r['task_size_mb']) for r in rows}) > 1:
        metrics=[('balance','fig8_load_balance'),('success_rate','fig9_offloading_success'),('qos','fig10_qos')]
        for metric,name in metrics:
            fig,ax=plt.subplots(figsize=(6,4))
            for algo in dict.fromkeys(r['algorithm'] for r in rows):
                group=sorted([r for r in rows if r['algorithm']==algo],key=lambda x:float(x['task_size_mb']))
                ax.plot([float(r['task_size_mb']) for r in group],[float(r[metric]) for r in group],'-o',label=algo.upper())
            ax.set(xlabel='Task size (MB)',ylabel=metric.replace('_',' ').title())
            ax.legend();fig.tight_layout();fig.savefig(out/f'{name}.png',dpi=180);plt.close(fig)
    else:
        fig,ax=plt.subplots(figsize=(6,4))
        labels=[f"{r['algorithm']}: {r['mode']}" for r in rows]
        ax.bar(np.arange(len(rows)),[float(r['reward']) for r in rows]);ax.set_xticks(np.arange(len(rows)),labels,rotation=30,ha='right')
        ax.set_ylabel('Mean evaluation reward');fig.tight_layout()
        fig.savefig(out/'policy_reward_comparison.png',dpi=180);plt.close(fig)

def plot_multiple_training(specs, out, figure):
    fig,ax=plt.subplots(figsize=(6,4))
    for spec in specs:
        if '=' not in spec:raise ValueError('Expect label=path/to/training.csv')
        label,path=spec.split('=',1)
        rows=sorted(read_csv(path),key=lambda r:int(r['episode']))
        ax.plot([int(r['episode']) for r in rows],
                [float(r['reward']) for r in rows],label=label)
    ax.set(xlabel='Training episode',ylabel='Mean training reward')
    ax.legend();ax.grid(True,alpha=.25);fig.tight_layout()
    name='fig6_scheme_convergence.png' if figure=='fig6' else 'fig7_algorithm_convergence.png'
    fig.savefig(out/name,dpi=180);plt.close(fig)

def main():
    p=argparse.ArgumentParser();p.add_argument('--input');p.add_argument('--output')
    p.add_argument('--training-csv', nargs='+', help='For figures 6/7: label=/path/to/training.csv')
    p.add_argument('--figure', choices=['fig6','fig7'], default='fig7')
    args=p.parse_args()
    if not args.input and not args.training_csv:
        p.error('Provide --input or --training-csv')
    input_path=Path(args.input) if args.input else Path(args.training_csv[0].split('=',1)[-1])
    out=Path(args.output) if args.output else input_path.parent.parent/'figures'
    out.mkdir(exist_ok=True,parents=True)
    if args.training_csv:
        plot_multiple_training(args.training_csv,out,args.figure)
        print('Figures saved:',out)
        return
    rows=read_csv(input_path)
    if not rows:raise SystemExit('No real results in input CSV')
    if 'experiment' in rows[0]:plot_throughput(rows,out)
    elif 'episode' in rows[0]:plot_training(rows,out)
    else:plot_policy_sweep(rows,out)
    print('Figures saved:',out)
if __name__=='__main__':main()
